"""
hd_constants.py

Constants for human design features.

Modified from original by MicFell at https://github.com/MicFell/human_design_engine/
from August 2025.
"""

# synchronize IGING and zodiac circle ->58°
# Human design systems start at gate 41, Aries, (source :Ra Uru BlackBook)
IGING_offset = 58  

# codes from swe-> dict([[i,swe.get_planet_name(i)] for i in range(0,23)])
SWE_PLANET_DICT = {"Sun":0,
                    "Earth":0, # Sun position -180 longitude
                    "Moon":1,
                    "North_Node":11, # Disussion whether mean or True node?! here North Node -> true Node
                    "South_Node":11, # North_Node position - 180 longitude
                    "Mercury":2,
                    "Venus":3,
                    "Mars":4,
                    "Jupiter":5,
                    "Saturn":6,
                    "Uranus":7,
                    "Neptune":8,
                    "Pluto":9,
                    "Chiron":15,
                    "Lilith": 12,
                   #'Pholus':16,
                   #'Ceres':17,
                   #'Pallas':18,
                   #'Juno':19,
                   #'Vesta':20,
                   }

SWE_ANGLE_DICT = {"ASC": 0,
                  "MC": 1,
                  "DSC": 0,  # ASC + 180
                  "IC": 1}  # MC + 180

IGING_CIRCLE_LIST =  [41, 19, 13, 49, 30, 55, 37, 63, 22, 36, 25, 17, 21, 51, 42, 3, 27, 24, 2, 23, 8, 
                      20, 16, 35, 45, 12, 15, 52, 39, 53, 62, 56, 31, 33, 7, 4, 29, 59, 40, 64, 47, 6, 
                      46, 18, 48, 57, 32, 50, 28, 44, 1, 43, 14, 34, 9, 5, 26, 11, 10, 58, 38, 54, 61, 60]

#legend ->HD=Head,AA=Anja, TT=Throat, GC=G_Center, SL = Sacral, SN = Spleen, SP = SolarPlexus, RT = Root
GATES_CHAKRA_DICT = {(64,47):("HD","AA"),
                     (61,24):("HD","AA"),
                     (63, 4):("HD","AA"),
                     (17,62):("AA","TT"),
                     (43,23):("AA","TT"),
                     (11,56):("AA","TT"),
                     (16,48):("TT","SN"),
                     (20,57):("TT","SN"),
                     (20,34):("TT","SL"),
                     (20,10):("TT","GC"),
                     (31, 7):("TT","GC"),
                     ( 8, 1):("TT","GC"),
                     (33,13):("TT","GC"),
                     (45,21):("TT","HT"),
                     (35,36):("TT","SP"),
                     (12,22):("TT","SP"),
                     (32,54):("SN","RT"),
                     (28,38):("SN","RT"),
                     (57,34):("SN","SL"),
                     (50,27):("SN","SL"),
                     (18,58):("SN","RT"),
                     (10,34):("GC","SL"),
                     (15, 5):("GC","SL"),
                     ( 2,14):("GC","SL"),
                     (46,29):("GC","SL"),
                     (10,57):("GC","SN"),
                     (25,51):("GC","HT"),
                     (59, 6):("SL","SP"),
                     (42,53):("SL","RT"),
                     ( 3,60):("SL","RT"),
                     ( 9,52):("SL","RT"),
                     (26,44):("HT","SN"),
                     (40,37):("HT","SP"),
                     (49,19):("SP","RT"),
                     (55,39):("SP","RT"),
                     (30,41):("SP","RT"),
                    }

CHAKRA_LIST = ["HD","AA","TT","GC","HT","SP","SN","SL","RT"]

CHAKRA_NAMES = {"HD": "Head",
                "AA": "Anja",
                "TT": "Throat",
                "GC": "G Center",
                "HT": "Heart",
                "SP": "Solar Plexus",
                "SN": "Spleen",
                "SL": "Sacral",
                "RT": "Root"}

CHANNEL_MEANING_DICT = {
                        (64,47):["Abstraction","D. of mental activity and clarity"],
                        (61,24):["Awereness", "D. of a thinker"],
                        (63, 4):["Logic","D. of mental muse? mixed with doubt"],
                        (17,62):["Acceptance","D. of an organizational being"],
                        (43,23):["Structuring","D. of individuality"],
                        (11,56):["Curiosity","D. of a searcher"],
                        (16,48):["The Wave Length","D. of a talent"],
                        (20,57):["The Brain Wave","D. of penetrating awareness"],
                        (20,34):["Charisma","D. where thoughts must become deeds"],
                        (32,54):["Transformation","D. of being driven"],
                        (28,38):["Struggle","D. of stubbornness "],
                        (18,58):["Judgment","D. of insatiability"],
                        (20,10):["Awakening","D. of commitment to higher principles"],
                        (31, 7):["The Alpha","For 'good' or 'bad', a d. of leadership"],
                        ( 8, 1):["Inspiration","The creative role model"],
                        (33,13):["The Prodigal","The d. of witness"],
                        (10,34):["Exploration","A d. of following one's convictions"],
                        (15, 5):["Rythm","A d. of being in the flow"],
                        ( 2,14):["The Beat","A d. of being the keeper of keys"],
                        (46,29):["Discovery","A d. of succeding where others fail"],
                        (10,57):["Perfected Form","A d. of survival"],
                        (57,34):["Power","A d. of an archetype"],
                        (50,27):["Preservation","A. d. of custodianship"],
                        (45,21):["Money","A d. of a materialist"],
                        (59, 6):["Mating","A d. focused on reproduction"],
                        (42,53):["Maturation","A d. of balanced developement,cyclic"],
                        ( 3,60):["Mutation","Energy which fluctuates and initiates, pulse"],
                        ( 9,52):["Concentration","A d. of determination, focused"],
                        (26,44):["Surrender","A d. of a transmitter"],
                        (25,51):["Initiation","A d. of needing to be first"],
                        (40,37):["Community","A d. of being part, seeking a whole"],
                        (35,36):["Transitoriness","A d. of a 'Jack of all Trades'"],
                        (12,22):["Openness","A d, of a social being"],
                        (49,19):["Synthesis","A d. of being sensitive"],
                        (55,39):["Emoting","A d. of moodiness"],
                        (30,41):["Recognition","A d. of focused energy"],
                        }

IC_CROSS_TYP = { 
                (1,3):"RAC",
                (1,4):"RAC",
                (2,4):"RAC",
                (2,5):"RAC",
                (3,5):"RAC",
                (3,6):"RAC",
                (4,6):"RAC",
                (4,1):"JXP",
                (5,1):"LAC",
                (5,2):"LAC",
                (6,2):"LAC",
                (6,3):"LAC",
                }

PROFILE_TYP = { 
                (1,3):"Investigator / Martyr",
                (1,4):"Investigator / Opportunist",
                (2,4):"Hermit / Opportunist",
                (2,5):"Hermit / Heretic",
                (3,5):"Martyr / Heretic",
                (3,6):"Martyr / Role Model",
                (4,6):"Opportunist / Role Model",
                (4,1):"Opportunist / Investigator",
                (5,1):"Heretic / Investigator",
                (5,2):"Heretic / Hermit",
                (6,2):"Role Model / Hermit",
                (6,3):"Role Model / Martyr",
                }

penta_dict = {
                31:[],
                8:[],
                33:[],
                7:[],
                1:[],
                13:[],
                15:[],
                2:[],
                46:[],
                5:[],
                14:[],
                29:[]
             }

circuit_typ_dict={
                    (24,61):"Knowledge",
					(23,43):"Knowledge",
					( 1, 8):"Knowledge",
					( 2,14):"Knowledge",
					( 3,60):"Knowledge",
					(39,55):"Knowledge",
					(12,22):"Knowledge",
					(28,38):"Knowledge",
					(20,57):"Knowledge",
					(10,34):"Centre",
					(25,51):"Centre",
					( 4,63):"Realize",
					(17,62):"Realize",
					( 7,31):"Realize",
					( 5,15):"Realize",
					( 9,52):"Realize",
					(18,58):"Realize",
					(16,48):"Realize",
					(47,64):"Sense",
					(11,56):"Sense",
					(13,33):"Sense",
					(29,46):"Sense",
					(42,53):"Sense",
					(30,41):"Sense",
					(35,36):"Sense",
					(32,54):"Ego",
					(26,44):"Ego",
					(19,49):"Ego",
					(37,40):"Ego",
					(21,45):"Ego",
					( 6,59):"Protect",
					(27,50):"Protect",
					(10,20):"Integration",
					(20,34):"Integration",
					(34,57):"Integration",
					(10,57):"Integration",
				 }
circuit_group_typ_dict = {
                        "Knowledge":"Individual",
						"Centre":"Individual",
						"Realize":"Collective",
						"Sense":"Collective",
						"Ego":"Tribal",
						"Protect":"Tribal",
						"Integration":"Integration",
                        }

awareness_stream_dict = {
						(58,18,48,16):"Taste",
						(38,28,67,20):"Intuition",
						(54,32,44,26):"Instinct",
						(41,30,36,35):"Feel",
						(39,55,22,12):"Emotion",
						(19,49,37,40):"Sensitivity",
						(64,47,11,56):"Realize/Meaning",
						(61,24,43,23):"Knowledge",
						(63, 4,17,62):"Understand"
						}
						
awareness_stream_group_dict = {
								"Taste":"Spleen",
								"Intuition":"Spleen",
								"Instinct":"Spleen",
								"Feel":"SolarPlexus",
								"Emotion":"SolarPlexus",
								"Sensitivity":"SolarPlexus",
								"Realize/Meaning":"Anja",
								"Knowledge":"Anja",
								"Understand":"Anja"
								}

DEFINITION_NAMES = {0: "No Definition",
                    1: "Single Definition",
                    2: "Split Definition",
                    3: "Triple Split Definition",
                    4: "Quadruple Split Definition"}

STRATEGIES = {"Generator": "Respond",
              "Manifesting Generator": "Respond",
              "Manifestor": "Inform and Initiate",
              "Projector": "Wait for Invitation",
              "Reflector": "Wait for a Lunar Cycle"}

THEMES = {"Generator": "Satisfaction/Frustration",
          "Manifesting Generator": "Satisfaction/Frustration",
          "Manifestor": "Peace/Anger",
          "Projector": "Success/Bitterness",
          "Reflector": "Surprise/Disappointment"}

IC_NAMES = {((1, 2), (7, 13)): "Right Angle Cross of The Sphinx 4",
            ((1, 2), (4, 49)): "Left Angle Cross of Defiance 2",
            ((2, 1), (13, 7)): "Right Angle Cross of The Sphinx 2",
            ((2, 1), (49, 4)): "Left Angle Cross of Defiance 1",
            ((3, 50), (60, 56)): "Right Angle Cross of Laws 1",
            ((3, 50), (41, 31)): "Left Angle Cross of Wishes 1",
            ((4, 49), (23, 43)): "Right Angle Cross of Explanation 3",
            ((4, 49), (8, 14)): "Left Angle Cross of Revolution 2",
            ((5, 35), (64, 63)): "Right Angle Cross of Consciousness 4",
            ((5, 35), (47, 22)): "Left Angle Cross of Separation 2",
            ((6, 36), (12, 11)): "Right Angle Cross of Eden 3",
            ((6, 36), (15, 10)): "Left Angle Cross of The Plane 2",
            ((7, 13), (2, 1)): "Right Angle Cross of The Sphinx 3",
            ((7, 13), (23, 43)): "Left Angle Cross of Masks 2",
            ((8, 14), (30, 29)): "Right Angle Cross of Contagion 2",
            ((8, 14), (55, 59)): "Left Angle Cross of Uncertainty 1",
            ((9, 16), (40, 37)): "Right Angle Cross of Planning 4",
            ((9, 16), (64, 63)): "Left Angle Cross of Identification 2",
            ((10, 15), (46, 25)): "Right Angle Cross of The Vessel of Love 4",
            ((10, 15), (18, 17)): "Left Angle Cross of Prevention 2",
            ((11, 12), (6, 36)): "Right Angle Cross of Eden 4",
            ((11, 12), (46, 25)): "Left Angle Cross of Education 2",
            ((12, 11), (36, 6)): "Right Angle Cross of Eden 2",
            ((12, 11), (25, 46)): "Left Angle Cross of Education 1",
            ((13, 7), (1, 2)): "Right Angle Cross of The Sphinx 1",
            ((13, 7), (43, 23)): "Left Angle Cross of Masks 1",
            ((14, 8), (29, 30)): "Right Angle Cross of Contagion 4",
            ((14, 8), (59, 55)): "Left Angle Cross of Uncertainty 2",
            ((15, 10), (25, 46)): "Right Angle Cross of The Vessel of Love 2",
            ((15, 10), (17, 18)): "Left Angle Cross of Prevention 1",
            ((16, 9), (37, 40)): "Right Angle Cross of Planning 2",
            ((16, 9), (63, 64)): "Left Angle Cross of Identification 1",
            ((17, 18), (58, 52)): "Right Angle Cross of Service 1",
            ((17, 18), (38, 39)): "Left Angle Cross of Upheaval 1",
            ((18, 17), (52, 58)): "Right Angle Cross of Service 3",
            ((18, 17), (39, 38)): "Left Angle Cross of Upheaval 2",
            ((19, 33), (44, 24)): "Right Angle Cross of The Four Ways 4",
            ((19, 33), (1, 2)): "Left Angle Cross of Refinement 2",
            ((20, 34), (55, 59)): "Right Angle Cross of The Sleeping Phoenix 1",
            ((20, 34), (37, 40)): "Left Angle Cross of Duality 1",
            ((21, 48), (38, 39)): "Right Angle Cross of Tension 1",
            ((21, 48), (54, 53)): "Left Angle Cross of Endeavor 1",
            ((22, 47), (26, 45)): "Right Angle Cross of Rulership 1",
            ((22, 47), (11, 12)): "Left Angle Cross of Informing 1",
            ((23, 43), (49, 4)): "Right Angle Cross of Explanation 2",
            ((23, 43), (30, 29)): "Left Angle Cross of Dedication 1",
            ((24, 44), (19, 33)): "Right Angle Cross of The Four Ways 1",
            ((24, 44), (13, 7)): "Left Angle Cross of Incarnation 1",
            ((25, 46), (10, 15)): "Right Angle Cross of The Vessel of Love 1",
            ((25, 46), (58, 52)): "Left Angle Cross of Healing 1",
            ((26, 45), (47, 22)): "Right Angle Cross of Rulership 4",
            ((26, 45), (6, 36)): "Left Angle Cross of Confrontation 2",
            ((27, 28), (41, 31)): "Right Angle Cross of The Unexpected 1",
            ((27, 28), (19, 33)): "Left Angle Cross of Alignment 1",
            ((28, 27), (31, 41)): "Right Angle Cross of The Unexpected 3",
            ((28, 27), (33, 19)): "Left Angle Cross of Alignment 2",
            ((29, 30), (8, 14)): "Right Angle Cross of Contagion 3",
            ((29, 30), (20, 34)): "Left Angle Cross of Industry 2",
            ((30, 29), (14, 8)): "Right Angle Cross of Contagion 1",
            ((30, 29), (34, 20)): "Left Angle Cross of Industry 1",
            ((31, 41), (27, 28)): "Right Angle Cross of The Unexpected 2",
            ((31, 41), (24, 44)): "Left Angle Cross of The Alpha 1",
            ((32, 42), (62, 61)): "Right Angle Cross of Maya 3",
            ((32, 42), (56, 60)): "Left Angle Cross of Limitation 2",
            ((33, 19), (24, 44)): "Right Angle Cross of The Four Ways 2",
            ((33, 19), (2, 1)): "Left Angle Cross of Refinement 1",
            ((34, 20), (59, 55)): "Right Angle Cross of The Sleeping Phoenix 4",
            ((34, 20), (40, 37)): "Left Angle Cross of Duality 2",
            ((35, 5), (63, 64)): "Right Angle Cross of Consciousness 2",
            ((35, 5), (22, 47)): "Left Angle Cross of Separation 1",
            ((36, 6), (11, 12)): "Right Angle Cross of Eden 1",
            ((36, 6), (10, 15)): "Left Angle Cross of The Plane 1",
            ((37, 40), (9, 16)): "Right Angle Cross of Planning 1",
            ((37, 40), (5, 35)): "Left Angle Cross of Migration 1",
            ((38, 39), (48, 21)): "Right Angle Cross of Tension 4",
            ((38, 39), (57, 51)): "Left Angle Cross of Individualism 2",
            ((39, 38), (21, 48)): "Right Angle Cross of Tension 2",
            ((39, 38), (51, 57)): "Left Angle Cross of Individualism 1",
            ((40, 37), (16, 9)): "Right Angle Cross of Planning 3",
            ((40, 37), (35, 5)): "Left Angle Cross of Migration 2",
            ((41, 31), (28, 27)): "Right Angle Cross of The Unexpected 4",
            ((41, 31), (44, 24)): "Left Angle Cross of The Alpha 2",
            ((42, 32), (61, 62)): "Right Angle Cross of Maya 1",
            ((42, 32), (60, 56)): "Left Angle Cross of Limitation 1",
            ((43, 23), (4, 49)): "Right Angle Cross of Explanation 4",
            ((43, 23), (29, 30)): "Left Angle Cross of Dedication 2",
            ((44, 24), (33, 19)): "Right Angle Cross of The Four Ways 3",
            ((44, 24), (7, 13)): "Left Angle Cross of Incarnation 2",
            ((45, 26), (22, 47)): "Right Angle Cross of Rulership 2",
            ((45, 26), (36, 6)): "Left Angle Cross of Confrontation 1",
            ((46, 25), (15, 10)): "Right Angle Cross of The Vessel of Love 3",
            ((46, 25), (52, 58)): "Left Angle Cross of Healing 2",
            ((47, 22), (45, 26)): "Right Angle Cross of Rulership 3",
            ((47, 22), (12, 11)): "Left Angle Cross of Informing 2",
            ((48, 21), (39, 38)): "Right Angle Cross of Tension 3",
            ((48, 21), (53, 54)): "Left Angle Cross of Endeavor 2",
            ((49, 4), (43, 23)): "Right Angle Cross of Explanation 1",
            ((49, 4), (14, 8)): "Left Angle Cross of Revolution 1",
            ((50, 3), (56, 60)): "Right Angle Cross of Laws 3",
            ((50, 3), (31, 41)): "Left Angle Cross of Wishes 2",
            ((51, 57), (54, 53)): "Right Angle Cross of Penetration 1",
            ((51, 57), (61, 62)): "Left Angle Cross of The Clarion 1",
            ((52, 58), (17, 18)): "Right Angle Cross of Service 2",
            ((52, 58), (21, 48)): "Left Angle Cross of Demands 1",
            ((53, 54), (51, 57)): "Right Angle Cross of Penetration 2",
            ((53, 54), (42, 32)): "Left Angle Cross of Cycles 1",
            ((54, 53), (57, 51)): "Right Angle Cross of Penetration 4",
            ((54, 53), (32, 42)): "Left Angle Cross of Cycles 2",
            ((55, 59), (34, 20)): "Right Angle Cross of The Sleeping Phoenix 1",
            ((55, 59), (9, 16)): "Left Angle Cross of Spirit 1",
            ((56, 60), (3, 50)): "Right Angle Cross of Laws 2",
            ((56, 60), (27, 28)): "Left Angle Cross of Distraction 1",
            ((57, 51), (53, 54)): "Right Angle Cross of Penetration 3",
            ((57, 51), (62, 61)): "Left Angle Cross of The Clarion 2",
            ((58, 52), (18, 17)): "Right Angle Cross of Service 4",
            ((58, 52), (48, 21)): "Left Angle Cross of Demands 2",
            ((59, 55), (20, 34)): "Right Angle Cross of The Sleeping Phoenix 3",
            ((59, 55), (16, 9)): "Left Angle Cross of Spirit 2",
            ((60, 56), (50, 3)): "Right Angle Cross of Laws 4",
            ((60, 56), (28, 27)): "Left Angle Cross of Distraction 2",
            ((61, 62), (32, 42)): "Right Angle Cross of Maya 4",
            ((61, 62), (50, 3)): "Left Angle Cross of Obscuration 2",
            ((62, 61), (42, 32)): "Right Angle Cross of Maya 2",
            ((62, 61), (3, 50)): "Left Angle Cross of Obscuration 1",
            ((63, 64), (5, 35)): "Right Angle Cross of Consciousness 1",
            ((63, 64), (26, 45)): "Left Angle Cross of Dominion 1",
            ((64, 63), (35, 5)): "Right Angle Cross of Consciousness 3",
            ((64, 63), (45, 26)): "Left Angle Cross of Dominion 2",
}

IC_JUX_NAMES = {
            ((1, 2), (4, 49)): "Juxtaposition Cross of Self-expression",
            ((2, 1), (49, 4)): "Juxtaposition Cross of The Driver",
            ((3, 50), (41, 31)): "Juxtaposition Cross of Mutation",
            ((4, 49), (8, 14)): "Juxtaposition Cross of Formulization",
            ((5, 35), (47, 22)): "Juxtaposition Cross of Habits",
            ((6, 36), (15, 10)): "Juxtaposition Cross of Conflict",
            ((7, 13), (23, 43)): "Juxtaposition Cross of Interaction",
            ((8, 14), (55, 59)): "Juxtaposition Cross of Contribution",
            ((9, 16), (64, 63)): "Juxtaposition Cross of Focus",
            ((10, 15), (18, 17)): "Juxtaposition Cross of Behavior",
            ((11, 12), (46, 25)): "Juxtaposition Cross of Ideas",
            ((12, 11), (25, 46)): "Juxtaposition Cross of Articulation",
            ((13, 7), (43, 23)): "Juxtaposition Cross of Listening",
            ((14, 8), (59, 55)): "Juxtaposition Cross of Empowering",
            ((15, 10), (17, 18)): "Juxtaposition Cross of Extremes",
            ((16, 9), (63, 64)): "Juxtaposition Cross of Experimentation",
            ((17, 18), (38, 39)): "Juxtaposition Cross of Opinions",
            ((18, 17), (39, 38)): "Juxtaposition Cross of Correction",
            ((19, 33), (1, 2)): "Juxtaposition Cross of Need",
            ((20, 34), (37, 40)): "Juxtaposition Cross of The Now",
            ((21, 48), (54, 53)): "Juxtaposition Cross of Control",
            ((22, 47), (11, 12)): "Juxtaposition Cross of Grace",
            ((23, 43), (30, 29)): "Juxtaposition Cross of Assimilation",
            ((24, 44), (13, 7)): "Juxtaposition Cross of Rationalization",
            ((25, 46), (58, 52)): "Juxtaposition Cross of Innocence",
            ((26, 45), (6, 36)): "Juxtaposition Cross of The Trickster",
            ((27, 28), (19, 33)): "Juxtaposition Cross of Caring",
            ((28, 27), (33, 19)): "Juxtaposition Cross of Risks",
            ((29, 30), (20, 34)): "Juxtaposition Cross of Commitment",
            ((30, 29), (34, 20)): "Juxtaposition Cross of Fates",
            ((31, 41), (24, 44)): "Juxtaposition Cross of Influence",
            ((32, 42), (56, 60)): "Juxtaposition Cross of Conservation",
            ((33, 19), (2, 1)): "Juxtaposition Cross of Retreat",
            ((34, 20), (40, 37)): "Juxtaposition Cross of Power",
            ((35, 5), (22, 47)): "Juxtaposition Cross of Experience",
            ((36, 6), (10, 15)): "Juxtaposition Cross of Crisis",
            ((37, 40), (5, 35)): "Juxtaposition Cross of Bargains",
            ((38, 39), (57, 51)): "Juxtaposition Cross of Opposition",
            ((39, 38), (51, 57)): "Juxtaposition Cross of Provocation",
            ((40, 37), (35, 5)): "Juxtaposition Cross of Denial",
            ((41, 31), (44, 24)): "Juxtaposition Cross of Fantasy",
            ((42, 32), (60, 56)): "Juxtaposition Cross of Completion",
            ((43, 23), (29, 30)): "Juxtaposition Cross of Insight",
            ((44, 24), (7, 13)): "Juxtaposition Cross of Alertness",
            ((45, 26), (36, 6)): "Juxtaposition Cross of Possession",
            ((46, 25), (52, 58)): "Juxtaposition Cross of Serendipity",
            ((47, 22), (12, 11)): "Juxtaposition Cross of Oppression",
            ((48, 21), (53, 54)): "Juxtaposition Cross of Depth",
            ((49, 4), (14, 8)): "Juxtaposition Cross of Principles",
            ((50, 3), (31, 41)): "Juxtaposition Cross of Values",
            ((51, 57), (61, 62)): "Juxtaposition Cross of Shock",
            ((52, 58), (21, 48)): "Juxtaposition Cross of Stillness",
            ((53, 54), (42, 32)): "Juxtaposition Cross of Beginnings",
            ((54, 53), (32, 42)): "Juxtaposition Cross of Ambition",
            ((55, 59), (9, 16)): "Juxtaposition Cross of Moods",
            ((56, 60), (27, 28)): "Juxtaposition Cross of Stimulation",
            ((57, 51), (62, 61)): "Juxtaposition Cross of Intuition",
            ((58, 52), (48, 21)): "Juxtaposition Cross of Vitality",
            ((59, 55), (16, 9)): "Juxtaposition Cross of Strategy",
            ((60, 56), (28, 27)): "Juxtaposition Cross of Limitation",
            ((61, 62), (50, 3)): "Juxtaposition Cross of Thinking",
            ((62, 61), (3, 50)): "Juxtaposition Cross of Detail",
            ((63, 64), (26, 45)): "Juxtaposition Cross of Doubts",
            ((64, 63), (45, 26)): "Juxtaposition Cross of Confusion",
}

